"""New model Table1

Revision ID: 1981d6a2c57d
Revises: 9e9fd867aea8
Create Date: 2024-05-16 17:25:48.694575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1981d6a2c57d'
down_revision: Union[str, None] = '9e9fd867aea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_relationship', sa.Column('is_initiator', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_relationship', 'is_initiator')
    # ### end Alembic commands ###
