"""New model Table

Revision ID: 9e9fd867aea8
Revises: 
Create Date: 2024-05-16 15:26:23.051740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e9fd867aea8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_private_chat',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_username', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['private_chat.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_username'], ['users.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'user_username')
    )
    op.create_table('users_relationship',
    sa.Column('friendship_id', sa.Integer(), nullable=False),
    sa.Column('user_username', sa.String(length=30), nullable=False),
    sa.Column('status_friendship', sa.Enum('friend_request', 'blocked', 'friend', name='friendshipstatus'), nullable=True),
    sa.ForeignKeyConstraint(['friendship_id'], ['friends.id_friendship'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_username'], ['users.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('friendship_id', 'user_username')
    )
    op.drop_constraint('friends_first_username_fkey', 'friends', type_='foreignkey')
    op.drop_constraint('friends_second_username_fkey', 'friends', type_='foreignkey')
    op.drop_column('friends', 'first_username')
    op.drop_column('friends', 'second_username')
    op.drop_constraint('two_users_chat', 'private_chat', type_='unique')
    op.drop_constraint('private_chat_second_username_fkey', 'private_chat', type_='foreignkey')
    op.drop_constraint('private_chat_first_username_fkey', 'private_chat', type_='foreignkey')
    op.drop_column('private_chat', 'first_username')
    op.drop_column('private_chat', 'second_username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('private_chat', sa.Column('second_username', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('private_chat', sa.Column('first_username', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.create_foreign_key('private_chat_first_username_fkey', 'private_chat', 'users', ['first_username'], ['username'])
    op.create_foreign_key('private_chat_second_username_fkey', 'private_chat', 'users', ['second_username'], ['username'])
    op.create_unique_constraint('two_users_chat', 'private_chat', ['first_username', 'second_username'])
    op.add_column('friends', sa.Column('second_username', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('friends', sa.Column('first_username', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.create_foreign_key('friends_second_username_fkey', 'friends', 'users', ['second_username'], ['username'])
    op.create_foreign_key('friends_first_username_fkey', 'friends', 'users', ['first_username'], ['username'])
    op.drop_table('users_relationship')
    op.drop_table('users_private_chat')
    # ### end Alembic commands ###
